### ISSUE TITLE
Updates To the site

### ISSUE THREAD

**Issue by Waynez80** [mspkvp/tk7movespretty#10]
Hello! Big fan of the site you created. It helped me learn to use the character King. However, i was wondering if you ever planned on updating the site any time soon? There have been a ton of new characters/updates to movesets, etc. Even if you don't plan on it, i created this github account to reach out and let you know how appreciative I am of your work. Thanks again!

**Comment by mspkvp** [comment]
Hey Wayne! Thanks for the support!
I've been postponing it, but it's in the works! I'm parsing all the info
from the sources (this one seems to be the most up-to-date
https://docs.google.com/spreadsheets/d/1EDWIwBAI36fomu2asF8DPze6pIooaTG0KUssl5gs1Jc/edit#gid=1449029616
)

I was plannig on rebuilding it, but I'm just going to prioritize the data
and update this version asap and then go back to the new version.

Cheers,
Mike

Waynez80 <notifications@github.com> escreveu no dia quarta, 6/02/2019 à(s)
21:30:

**Comment by Waynez80** [comment]
This is SO awesome to hear! Thank you for the info and the quick update! Can't wait to see what  you end up with as the final product!!
