### ISSUE TITLE
Character Thumbnails

### ISSUE THREAD

**Issue by aromahyang** [mspkvp/tk7movespretty#15]
Hi, I am fascinated by this project.
I have a question that how you make character thumbnails.
Did you make every thumbnail on your own?
If so, how did you make them? Did you use Photoshop and crop images of character by 448 x 248?
Or did you download them from a specific site?
Thanks in advance!

**Comment by mspkvp** [comment]
Hey, sorry I haven't replied sooner, I haven't paying must attention to my repos lately.
So, for characters I grabbed the major full size files from the official Tekken 7 website, then I created a template in Photoshop and just resized every character image in that. Then I just exported them to PNG and voilà ! :)
I think I have the template somewhere if you want it, but you should know I'm not a pro or anything in PS ^^
